### ISSUE TITLE
Include source clip

### ISSUE THREAD

**Issue by SystematicError** [Lrakulka/Master_Diploma#1]
Hey!

I made a similar AI and I was searching for a good source clip. The one you showed on your [youtube video](https://www.youtube.com/watch?v=VRMiswPv_to) is perfect, would you mind sharing this?

**Comment by Lrakulka** [comment]
Hi

You can find the source video [here](https://www.reddit.com/r/holdmyfeedingtube/comments/eqmqmt/hmft_after_i_get_launched/)
I don't know how to download it from Reddit, but for sure it's possible.
